name: apple-health-exporter
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py36_0
- conda-forge::feather-format=0.3.1=py36_1
- conda-forge::icu=58.1=1
- conda-forge::libiconv=1.14=4
- conda-forge::libxml2=2.9.4=4
- conda-forge::libxslt=1.1.29=3
- conda-forge::lxml=3.7.3=py36_0
- conda-forge::ncurses=5.9=10
- conda-forge::openssl=1.0.2h=3
- conda-forge::pandas=0.19.2=np112py36_1
- conda-forge::pip=9.0.1=py36_0
- conda-forge::python=3.6.0=2
- conda-forge::python-dateutil=2.6.0=py36_0
- conda-forge::pytz=2016.10=py36_0
- conda-forge::readline=6.2=0
- conda-forge::setuptools=33.1.0=py36_0
- conda-forge::six=1.10.0=py36_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::wheel=0.29.0=py36_0
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.11=0
- mkl=2017.0.1=0
- numpy=1.12.0=py36_0
